OnlineExamSystem/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineExamSystem.Data;

namespace OnlineExamSystem.Controllers
{
    public class RoleController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoleController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var roles = _context.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }
        // Create a new Role
        [HttpPost]
        public IActionResult Create(IdentityRole Role)
        {
            _context.Roles.Add(Role);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        // GET: Role/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .SingleOrDefaultAsync(m => m.Id == id.ToString() );
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Role/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _context.Roles.SingleOrDefaultAsync(m => m.Id == id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineExamSystem/Views/Role/Create.cshtml
@model IdentityRole
@{
    ViewData["Title"] = "Create";
}
<h2>Create</h2>
<style type="text/css">
    #tbrole, .C {
        border: double;
    }
</style>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <form class="form-horizontal">
            <table class="table table-bordered table-hover">
                <tr>
                    <td class="C">Enter Role Name To be Created:</td>
                    <td class="C">
                        @Html.EditorFor(m => m.Name)
                    </td>
                </tr>
            </table>
            <input type="submit" class="form-control btn btn-primary" value="Create Role"/><br/>
        </form>
    </div>
</div>

OnlineExamSystem/Views/Role/Delete.cshtml
@model IdentityRole
    ViewData["Title"] = "Delete";
}
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Role</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Name" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

OnlineExamSystem/Views/Role/Index.cshtml
@model List<IdentityRole>
@{
    ViewData["Title"] = "Index";
    var i = 1;
}

<h2 style="text-align: center">Availabe Roles for Application</h2><br/>
<section class="col-sm-6">
    <table class="table table-bordered">
        @*@Html.ActionLink("Create Role", "Create", "Role")*@
        <div>
            <a asp-action="CreateRole" asp-controller="Account">Create Role</a>
        </div>
    </table>
</section>
<section class="col-sm-6">
    <table class="table table-bordered">
        @*@Html.ActionLink("Assign Role To User","CreateRole","Account")*@
        <div>
            <a asp-action="AssignRole" asp-controller="Account">Assign Role To User</a>
        </div>
    </table>
</section>
<br/>
<table class="table table-bordered table-hover table-striped">
    <tr>
        <th>S.I</th>
        <th>Role Name</th>
        <th>Action</th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td class="C">@i</td>
        <td class="C">@item.Name</td>
        <td><a asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
    </tr>
        i++;
    }
</table>