OnlineExamSystem/ViewModels/ExamQuestion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineExamSystem.ViewModels
{
    public class ExamQuestion
    {
        [Key]
        public string Title { get; set; }
        public int QuestionId { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string CorrectAnswer { get; set; }
    }
}

OnlineExamSystem/Controllers/ExamQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineExamSystem.Data;
using OnlineExamSystem.Models;

namespace OnlineExamSystem.Controllers
{
    public class ExamQuestionsController : Controller
    {
        private readonly ApplicationDbContext db;

        public ExamQuestionsController(ApplicationDbContext context)
        {
            db = context;
        }


        public async Task<IActionResult> CSharp(int? page)
        {
            IQueryable<Question> question = db.Question;
            if (page == null) page = 1;

            var query = (from q in db.Question
                         where q.ExamID == 1
                         select new Question
                         {
                             Title = q.Title,
                             Option1 = q.Option1,
                             Option2 = q.Option2,
                             Option3 = q.Option3,
                             Option4 = q.Option4,
                             CorrectAnswer= q.CorrectAnswer,
                             QuestionId = q.QuestionId
                         }).ToList();
            ViewBag.result = query;

            int pageSize = 3;
            return View(await PaginatedList<Question>.CreateAsync(question.AsNoTracking(), (int)page, pageSize));
        }


        public async Task<IActionResult> SQLSERVER(int? page)
        {
            IQueryable<Question> question = db.Question;
            if (page == null) page = 1; ;

            var query = (from q in db.Question
                         where q.ExamID == 2
                         select new Question
                         {
                             Title = q.Title,
                             Option1 = q.Option1,
                             Option2 = q.Option2,
                             Option3 = q.Option3,
                             Option4 = q.Option4,
                             CorrectAnswer = q.CorrectAnswer,
                             QuestionId = q.QuestionId
                         }).ToList();

            ViewBag.result = query;

            int pageSize = 3;
            return View(await PaginatedList<Question>.CreateAsync(question.AsNoTracking(), (int)page, pageSize));
        }

        public async Task<IActionResult> Index()
        {
            //IQueryable<Exam> exam = db.Exam;
            //if (page == null) page = 1;
            //int pageSize = 3;
            //return View(await PaginatedList<Exam>.CreateAsync(exam.AsNoTracking(), (int)page, pageSize));

            return View();
        }
    }
}

OnlineExamSystem/Views/ExamQuestions/CSharp.cshtml
@model PaginatedList<OnlineExamSystem.Models.Question>
@{
    ViewData["Title"] = "CSharp";
    var page = Model.PageIndex;
    var totpage = Model.TotalPages;
    var PrevPage = "";
    var NextPage = "";

    var i = (page-1) * 3 + 1;

    if (page <= 1)
    {
        PrevPage = "disabled";
    }

    if(page>=totpage)
    {
        NextPage = "disabled";
    }
}
<h2>CSharp</h2>

    @foreach (var item in ViewBag.result)
    {

        <div id="q_@item.QuestionId">
            <p style="font-size: 120%">Question @i :@item.Title </p>
            <form>               
                    A: <input type="radio" name="option" value="A">@item.Option1<br >
                    B: <input type="radio" name="option" value="B">@item.Option2<br >
                    C: <input type="radio" name="option" value="C">@item.Option3<br >
                    D: <input type="radio" name="option" value="D">@item.Option4<br/> 

                @* <input id="r_@item.QuestionId" type="button" value="ShowResult" /><br /><br />*@
            </form> <br />
            <P id="result" hidden> Correct Answer: @item.CorrectAnswer</P>
            <input id="qId" type="text" hidden value="@item.QuestionId" />
        </div>
        i++;
        //List<string> Qlist = new List<string>();
        //Qlist.Add("q_'" + @item.QuestionId + "'");

    }
<div>
    <form class="form-inline" method="get" asp-action="index">
        <a asp-route-page="@(page-1)" class="btn btn-primary @PrevPage">Prev</a>
        <a asp-route-page="@(page-1)" class="btn btn-primary @PrevPage">@(page - 1) </a>
        <a asp-route-page="@(page-1)" class="btn btn-primary ">@(page) </a>
        <a asp-route-page="@(page+1)" class="btn btn-primary @NextPage">@(page + 1) </a>
        <a asp-route-page="@(page+1)" class="btn btn-primary @NextPage">Next</a>

        @*<input type="number" id="cpage" class="form-control" value="@ViewBag.page" />*@
    </form>
</div>
<br/>
<div>
    <a asp-action="Index">Back to List</a>
</div>

OnlineExamSystem/Views/ExamQuestions/Index.cshtml
@{
    ViewData["Title"] = "Exam Name";
}

<h3>Exam Name</h3>

<table>
    <tr>
       
        <td>@Html.ActionLink("C#","CSharp","ExamQuestions")<td>
        
        
    </tr>
    <tr>
        <td>@Html.ActionLink("SQL", "SQLSERVER", "ExamQuestions")<td>
    </tr>
</table>

OnlineExamSystem/Views/ExamQuestions/SQLSERVER.cshtml
@model PaginatedList<OnlineExamSystem.Models.Question>
@{
    ViewData["Title"] = "SQLSERVER";
    
    var page = Model.PageIndex;
    var totpage = Model.TotalPages;
    var PrevPage = "";
    var NextPage = "";

    var i = (page - 1) * 3 + 1;

    if (page <= 1)
    {
        PrevPage = "disabled";
    }

    if (page >= totpage)
    {
        NextPage = "disabled";
    }

}

<h2>SQLSERVER</h2>

@foreach (var item in ViewBag.result)
{
    

    <div id="q_@item.QuestionId">
        <p style="font-size: 120%">Question @i :@item.Title </p>
        <form>
            A: <input type="radio" name="option" value="A">@item.Option1<br>
            B: <input type="radio" name="option" value="B">@item.Option2<br>
            C: <input type="radio" name="option" value="C">@item.Option3<br>
            D: <input type="radio" name="option" value="D">@item.Option4<br>
        </form><br />
        <P id="result" hidden> Correct Answer: @item.CorrectAnswer</P>
        <input id="qId" type="text" hidden value="@item.QuestionId" />
    </div>

    i++;

}

<div>
    <form class="form-inline" method="get" asp-action="index">
        <a asp-route-page="@(page-1)" class="btn btn-primary @PrevPage">Prev</a>
        <a asp-route-page="@(page-1)" class="btn btn-primary @PrevPage">@(page - 1) </a>
        <a asp-route-page="@(page-1)" class="btn btn-primary ">@(page) </a>
        <a asp-route-page="@(page+1)" class="btn btn-primary @NextPage">@(page + 1) </a>
        <a asp-route-page="@(page+1)" class="btn btn-primary @NextPage">Next</a>

        @*<input type="number" id="cpage" class="form-control" value="@ViewBag.page" />*@
    </form>
</div>
<br />  
<div>
    <a asp-action="Index">Back to List</a>
</div>